### ISSUE TITLE
swift 4.0.3 file access problem under Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by attilaM68K** [cui-unige/semantique#2] opened 2018-02-20 12:44 UTC
![screenshot_20180220_133532](https://user-images.githubusercontent.com/32138106/36424391-6bb482ba-1643-11e8-9aaf-8320c9d40867.png)
I have this exact terminal output. Once I tried running with sudo, but in this case all the tests fail. Otherwise it gives this error: `<unknown>:0: error: cannot open file '/usr/lib/swift/CoreFoundation/module.modulemap': Permission denied
`
I used the curl command as indicated in the tutorial to install swift onto a fresh install of Ubuntu 16.04LTS

**Comment by saucisson** [comment] 2018-02-20 12:56
This issue is currently under investigation.

**Comment by saucisson** [comment] 2018-02-20 14:28
The problem is now fixed. It was in fact the conjunction of several problems:

* missing dependencies on libpython2.7 and libcurl;
* wrong permissions on the swift installation;
* incompatible use of URLs.

The  `anzen` source code examples are now given as string constants within the `semantique` module.

Please rerun the `install` script and update your repository to fix the problem.

**Closed** 2018-02-20 14:28 UTC
